// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezzmlcffmxsnyxuiawxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6em1sY2ZmbXhzbnl4dWlhd3h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDA1MzcsImV4cCI6MjA2MDU3NjUzN30.IZjGM42ZvUnoX4yt-sdYxZQFrm528AfFY9hz0iGA-kI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);